apiVersion: v1
kind: ConfigMap
metadata:
  name: event-pipeline-config
  namespace: default
data:
  POSTGRES_HOST: "postgres-service"
  POSTGRES_PORT: "5432"
  POSTGRES_DB:   "events"
  POSTGRES_USER: "postgres"
  EVENT_RATE:    "50"
  EVENT_DURATION: "60"
